### ISSUE TITLE
change the nethernite wand be smithed

### ISSUE THREAD

**Issue by ghost** [Draylar/staff-of-building#11]
for consistency make the nethernite wand be crafted with a diamond wand and netherite ingot in a smiting table.

also 1.16?

**Comment by ghost** [comment]
nvm it's 1.16 already -.-, but my issue still stands

**Comment by FewerFlaws** [comment]
I'd also like to see this change.  The staff of building matches vanilla tools better than Builder Wands except for this one inconsistency.

**Comment by Draylar** [comment]
Fixed in 1.2.4, thanks :)
