### ISSUE TITLE
Fabric Version on the forge website?

### ISSUE THREAD

**Issue by PeacefulSand** [Draylar/staff-of-building#13]
Hi, I have a problem. On the forge website, you have posted a version of this that works with fabric for 1.16.5, but the crafting recipes listed here don't seem to work. Is there any reason for this?

**Comment by Draylar** [comment]
Use a mod like [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) to confirm the recipes are being loaded. The only incorrect recipe on the README page is the Netherite one. If this doesn't help you, please upload your game log to a service like [pastebin](https://pastebin.com/).
