### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Athentas** [Draylar/staff-of-building#22]
i don't know what this is
[crash-2021-06-29_09.28.34-client.txt](https://github.com/Draylar/staff-of-building/files/6734657/crash-2021-06-29_09.28.34-client.txt)

**Comment by Draylar** [comment]
Oops, should be fixed in [1.3.2](https://www.curseforge.com/minecraft/mc-mods/staff-of-building/files/3369392). Thank you for letting me know.

**Comment by Athentas** [comment]
ok thanks

**Comment by Athentas** [comment]
i dont get how it  works
