### ISSUE TITLE
Chinese(Simplified) Translation

### ISSUE THREAD

**Issue by Lechiny** [Draylar/staff-of-building#7]
I made a Chinese translation for myself, but if you need this just take it.. though my English is not very professional
https://drive.google.com/file/d/1uxoVb7-OMotx-0rciwPdTTq1CCGuz-7_/view?usp=sharing

**Comment by Draylar** [comment]
The mod seems to have a zn_cn translation submitted by another user already (might want to try updating to get those if you aren't on the latest version)-- thank you for helping out, though!
