### ISSUE TITLE
has incompatible changes at opcode 1789 in callback net/minecraft/class_761::renderWandHighlight.

### ISSUE THREAD

**Issue by chefvortivask123** [Draylar/staff-of-building#8]
Love this mod but it is incompatible with OptiFine

**Comment by Draylar** [comment]
Yes, nothing I can do about that, OptiFine is most likely obliterating that portion of the method out of existence, or something along those lines (at least, that's _normally_ how it ends up). My hook is only a [peaceful inject](https://github.com/Draylar/staff-of-building/blob/1cf5bb20cedc7fb5b2993d577ffcbf82511e7d26/src/main/java/draylar/staffofbuilding/mixin/WorldRendererMixin.java#L51). This would be on them to fix.

Haven't tested for compatibility, but [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium) and [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium) are far less invasive options with better results.
